Changes for installation of test environment
oikeusministerio/docsbox pull request #10
Opened 2018-10-29 13:43 UTC by nunomsfranco

- Updated travis.yml file for automated tests
- deleted docs/tests/docker-compose.yml there is no need for this docker-compose file, tests can be run with command "sudo docker-compose run web nosetests"
- updated main docker-compose file & ./docsbox Dockerfile

2018-10-29 14:10 UTC, numsu approved these changes
lgtm, but the build didn't seem to run ok :p

2018-10-29 14:11 UTC, numsu commented
Also change the readme's build info to point to the correct one

2018-11-06 13:34 UTC, numsu requested changes

2018-11-06 13:34 UTC, numsu commented on .travis.yml
> +- docker push ${IMAGE_REPO}:latest
Add a specific version to the environment variables to push.

2018-11-06 14:26 UTC, nunomsfranco commented on .travis.yml
> +- docker push ${IMAGE_REPO}:latest
I added a new variable so it can changed easily

2018-11-06 15:02 UTC, numsu approved these changes

2018-11-07 14:51 UTC, merged