SSY-6029 dev container
oikeusministerio/docsbox pull request #85
Opened 2024-12-31 14:47 UTC by FilPinto

2025-01-13 07:53 UTC, jonimarkkula approved these changes

2025-01-14 07:41 UTC, numsu requested changes

2025-01-14 07:41 UTC, numsu commented on README.md
> +    a. MEDIA_PATH: "/workspaces/docsbox/media/"
Why not add these as environment variables in the devcontainer.json?

2025-01-14 07:41 UTC, numsu commented on README.md
> +1. Initiate the redis container that it is defined on the docker-compose file
To make it simpler, could we integrate a docker-compose with the dev container so that it will start redis along with the dev container? Maybe also use a non-standard port for redis so that it doesn't interfere with another redis instance that might already be running

2025-01-20 08:20 UTC, FilPinto commented on README.md
> +    a. MEDIA_PATH: "/workspaces/docsbox/media/"
Changed to be part of the devcontainer.json definition

2025-01-20 11:22 UTC, FilPinto commented on README.md
> +1. Initiate the redis container that it is defined on the docker-compose file
I refactored to make it more simpler and docker-composer based

2025-01-21 09:40 UTC, merged